[2025-05-18T20:30:58.324+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts manual__2025-05-18T20:30:57.792753+00:00 [queued]>
[2025-05-18T20:30:58.329+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts manual__2025-05-18T20:30:57.792753+00:00 [queued]>
[2025-05-18T20:30:58.329+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-18T20:30:58.339+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): parse_channel_posts> on 2025-05-18 20:30:57.792753+00:00
[2025-05-18T20:30:58.345+0000] {standard_task_runner.py:60} INFO - Started process 231 to run task
[2025-05-18T20:30:58.350+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'telegram_summary_channel_1137503644', 'parse_channel_posts', 'manual__2025-05-18T20:30:57.792753+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator.py', '--cfg-path', '/tmp/tmpnzienug6']
[2025-05-18T20:30:58.352+0000] {standard_task_runner.py:88} INFO - Job 60: Subtask parse_channel_posts
[2025-05-18T20:30:58.400+0000] {task_command.py:423} INFO - Running <TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts manual__2025-05-18T20:30:57.792753+00:00 [running]> on host e5cd1b16e7bb
[2025-05-18T20:30:58.462+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='telegram_summary_channel_1137503644' AIRFLOW_CTX_TASK_ID='parse_channel_posts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-18T20:30:57.792753+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-18T20:30:57.792753+00:00'
[2025-05-18T20:30:58.514+0000] {docker.py:359} INFO - Starting docker container from image telegram_parser_task:latest
[2025-05-18T20:30:58.821+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [INFO] [Parser] - Запуск основного асинхронного процесса парсера (локальный или прямой вызов)...
[2025-05-18T20:30:58.822+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [DEBUG] [Parser] - Using selector: EpollSelector
[2025-05-18T20:30:58.822+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [INFO] [Parser] - --- Запуск скрипта парсера (Airflow Task) ---
[2025-05-18 20:30:58] [INFO] [Parser] - Целевой канал (Telethon ID): https://t.me/trader_chernyh
[2025-05-18 20:30:58] [INFO] [Parser] - Числовой ID канала (из конфига DAG для XCom/DB): 1137503644
[2025-05-18 20:30:58] [INFO] [Parser] - Целевая дата парсинга: 2025-05-18
[2025-05-18 20:30:58] [INFO] [Parser] - Попытка подключения к БД (1/5): host=postgres_results_db_service port=5432 dbname=parsing_results user=parser_user
[2025-05-18T20:30:58.828+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [INFO] [Parser] - Успешное подключение к БД!
[2025-05-18 20:30:58] [INFO] [Parser] - Проверка/создание таблицы 'telegram_messages'...
[2025-05-18T20:30:58.832+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [INFO] [Parser] - Схема БД 'telegram_messages' проверена/обновлена.
[2025-05-18 20:30:58] [INFO] [Parser] - Инициализация Telegram клиента с сессией: /app/session/my_telegram_session
[2025-05-18T20:30:58.832+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [INFO] [Parser] - Файл сессии '/app/session/my_telegram_session.session' существует: True
[2025-05-18T20:30:58.833+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [INFO] [Parser] - Подключение к Telegram...
[2025-05-18T20:30:58.833+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [INFO] [Parser] - Connecting to 149.154.167.51:443/TcpFull...
[2025-05-18 20:30:58] [DEBUG] [Parser] - Connection attempt 1...
[2025-05-18T20:30:58.893+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [DEBUG] [Parser] - Connection success!
[2025-05-18 20:30:58] [DEBUG] [Parser] - Starting send loop
[2025-05-18 20:30:58] [DEBUG] [Parser] - Starting receive loop
[2025-05-18 20:30:58] [INFO] [Parser] - Connection to 149.154.167.51:443/TcpFull complete!
[2025-05-18T20:30:58.900+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18 20:30:58] [DEBUG] [Parser] - Assigned msg_id = 7505885958190002124 to InvokeWithLayerRequest (fff2cbd953a0)
[2025-05-18 20:30:58] [DEBUG] [Parser] - Encrypting 1 message(s) in 80 bytes for sending
[2025-05-18T20:30:58.900+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18 20:30:58] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18 20:30:58] [DEBUG] [Parser] - Receiving items from the network...
[2025-05-18T20:30:58.960+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [DEBUG] [Parser] - Handling bad salt for message 7505885958190002124
[2025-05-18 20:30:58] [DEBUG] [Parser] - 1 message(s) will be resent
[2025-05-18 20:30:58] [DEBUG] [Parser] - Receiving items from the network...
[2025-05-18 20:30:58] [DEBUG] [Parser] - Assigned msg_id = 7505885958430887860 to InvokeWithLayerRequest (fff2cbd953a0)
[2025-05-18 20:30:58] [DEBUG] [Parser] - Encrypting 1 message(s) in 80 bytes for sending
[2025-05-18T20:30:58.960+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18T20:30:58.960+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18 20:30:58] [DEBUG] [Parser] - Assigned msg_id = 7505885958431441944 to MsgsAck (fff2cb9f30d0)
[2025-05-18 20:30:58] [DEBUG] [Parser] - Encrypting 1 message(s) in 36 bytes for sending
[2025-05-18T20:30:58.960+0000] {docker.py:429} INFO - [2025-05-18 20:30:58] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18 20:30:58] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18T20:30:59.019+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Handling container
[2025-05-18 20:30:59] [DEBUG] [Parser] - Handling new session created
[2025-05-18 20:30:59] [DEBUG] [Parser] - Handling acknowledge for [7505885958430887860]
[2025-05-18 20:30:59] [DEBUG] [Parser] - Receiving items from the network...
[2025-05-18T20:30:59.053+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Handling RPC result for message 7505885958430887860
[2025-05-18T20:30:59.053+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Receiving items from the network...
[2025-05-18 20:30:59] [DEBUG] [Parser] - Assigned msg_id = 7505885959099006936 to GetUsersRequest (fff2cb9f3310)
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypting 1 message(s) in 32 bytes for sending
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18 20:30:59] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18 20:30:59] [DEBUG] [Parser] - Assigned msg_id = 7505885959099639220 to MsgsAck (fff2ccc74040)
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypting 1 message(s) in 60 bytes for sending
[2025-05-18T20:30:59.054+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18 20:30:59] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18T20:30:59.213+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Handling RPC result for message 7505885959099006936
[2025-05-18 20:30:59] [DEBUG] [Parser] - Receiving items from the network...
[2025-05-18T20:30:59.213+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Assigned msg_id = 7505885959738271996 to GetStateRequest (fff2cbd953a0)
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypting 1 message(s) in 20 bytes for sending
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18 20:30:59] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18 20:30:59] [DEBUG] [Parser] - Assigned msg_id = 7505885959738917632 to MsgsAck (fff2cbaa9e20)
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypting 1 message(s) in 36 bytes for sending
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18 20:30:59] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18T20:30:59.360+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Handling RPC result for message 7505885959738271996
[2025-05-18 20:30:59] [DEBUG] [Parser] - Receiving items from the network...
[2025-05-18T20:30:59.360+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Assigned msg_id = 7505885960326830192 to GetDifferenceRequest (fff2cbd953a0)
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypting 1 message(s) in 36 bytes for sending
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18 20:30:59] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18T20:30:59.361+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Assigned msg_id = 7505885960327329920 to MsgsAck (fff2cb9f33d0)
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypting 1 message(s) in 36 bytes for sending
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18 20:30:59] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18T20:30:59.496+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Handling RPC result for message 7505885960326830192
[2025-05-18 20:30:59] [DEBUG] [Parser] - Receiving items from the network...
[2025-05-18T20:30:59.496+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Assigned msg_id = 7505885960868990228 to GetUsersRequest (fff2cbaa9c70)
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypting 1 message(s) in 32 bytes for sending
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18 20:30:59] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18T20:30:59.496+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Assigned msg_id = 7505885960869992540 to MsgsAck (fff2cb9f3ca0)
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypting 1 message(s) in 36 bytes for sending
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18 20:30:59] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18T20:30:59.660+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Handling RPC result for message 7505885960868990228
[2025-05-18 20:30:59] [DEBUG] [Parser] - Receiving items from the network...
[2025-05-18T20:30:59.661+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [INFO] [Parser] - Успешно подключен к Telegram как Ильяс (ID: 1257870016).
[2025-05-18 20:30:59] [INFO] [Parser] - Начало парсинга канала 'https://t.me/trader_chernyh' за дату 2025-05-18
[2025-05-18 20:30:59] [INFO] [Parser] - Получение информации о канале 'https://t.me/trader_chernyh'...
[2025-05-18T20:30:59.662+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Assigned msg_id = 7505885961531284616 to ResolveUsernameRequest (fff2cb9f3340)
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypting 1 message(s) in 40 bytes for sending
[2025-05-18T20:30:59.662+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18 20:30:59] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18 20:30:59] [DEBUG] [Parser] - Assigned msg_id = 7505885961533590600 to MsgsAck (fff2cbaa9d90)
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypting 1 message(s) in 36 bytes for sending
[2025-05-18T20:30:59.662+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18 20:30:59] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18T20:30:59.830+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Handling RPC result for message 7505885961531284616
[2025-05-18T20:30:59.831+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Receiving items from the network...
[2025-05-18T20:30:59.831+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [INFO] [Parser] - Канал найден: 'Евгений Черных и 401🍋' (ID: 1137503644)
[2025-05-18 20:30:59] [INFO] [Parser] - Итерация сообщений с offset_date=2025-05-19T00:00:00+00:00...
[2025-05-18T20:30:59.831+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Assigned msg_id = 7505885962206338212 to GetHistoryRequest (fff2cb9f3e50)
[2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypting 1 message(s) in 72 bytes for sending
[2025-05-18T20:30:59.831+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18 20:30:59] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18 20:30:59] [DEBUG] [Parser] - Assigned msg_id = 7505885962207448288 to MsgsAck (fff2cb9f3df0)
[2025-05-18T20:30:59.831+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypting 1 message(s) in 36 bytes for sending
[2025-05-18T20:30:59.831+0000] {docker.py:429} INFO - [2025-05-18 20:30:59] [DEBUG] [Parser] - Encrypted messages put in a queue to be sent
[2025-05-18 20:30:59] [DEBUG] [Parser] - Waiting for messages to send...
[2025-05-18T20:31:00.251+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [DEBUG] [Parser] - Handling RPC result for message 7505885962206338212
[2025-05-18T20:31:00.264+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [DEBUG] [Parser] - Receiving items from the network...
[2025-05-18T20:31:00.266+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [INFO] [Parser] - Достигнуто начало дня 2025-05-18. Завершение итерации.
[2025-05-18 20:31:00] [INFO] [Parser] - Парсинг завершен. Получено сообщений: 2
[2025-05-18 20:31:00] [INFO] [Parser] - Список сообщений развернут.
[2025-05-18 20:31:00] [INFO] [Parser] - Успешно получено 2 сообщений из Telegram.
[2025-05-18 20:31:00] [INFO] [Parser] - Начало сохранения 2 сообщений в БД...
[2025-05-18T20:31:00.266+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [DEBUG] [Parser] - Не удалось декодировать bytes (длина: 29) как UTF-8, используется base64.
[2025-05-18 20:31:00] [DEBUG] [Parser] - Не удалось декодировать bytes (длина: 148) как UTF-8, используется base64.
[2025-05-18T20:31:00.266+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [DEBUG] [Parser] - Данные для вставки (ID: 9668): {'message_id': 9668, 'channel_id': 1137503644, 'message_date': datetime.datetime(2025, 5, 18, 9, 30, 40, tzinfo=datetime.timezone.utc), 'text': '**Ну что, коллеги, котлету зажарили? ****😁****\n**\nПомните, как на прошлой неделе говорил: **уровень 2780 по индексу надо выкупать?**\n\n✅ Уровень устоял. Кто успел — красавчик. \n\n**Можете смело брать с полки пирожок. С вареньем, не с капустой.\n**\nНО! Мы отскочили. И я уже вижу зону, где могут начать падать акции.\n\nВ новом ролике рассказал об этом 👇\n\n[**➡️ Ютуб**](https://youtu.be/5AwSbmokQz8)\n\n[**➡️ Рутуб**](https://rutube.ru/video/5ee7f6f9a8012d868d2e43ecf69c6ba2/)\n\n[**➡️ ВК.видео**](https://vk.com/trader_chernyh?z=video-98605354_456239285%2F2864508e17832f796a%2Fpl_wall_314989763)', 'sender_id': -1001137503644, 'views': 22666, 'forwards': 37, 'is_reply': False, 'reply_to_msg_id': None, 'has_media': True, 'raw_data_type': 'Json'}
[2025-05-18T20:31:00.267+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [DEBUG] [Parser] - Не удалось декодировать bytes (длина: 29) как UTF-8, используется base64.
[2025-05-18 20:31:00] [DEBUG] [Parser] - Не удалось декодировать bytes (длина: 136) как UTF-8, используется base64.
[2025-05-18 20:31:00] [DEBUG] [Parser] - Не удалось декодировать bytes (длина: 29) как UTF-8, используется base64.
[2025-05-18 20:31:00] [DEBUG] [Parser] - Не удалось декодировать bytes (длина: 137) как UTF-8, используется base64.
[2025-05-18T20:31:00.267+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [DEBUG] [Parser] - Не удалось декодировать bytes (длина: 29) как UTF-8, используется base64.
[2025-05-18 20:31:00] [DEBUG] [Parser] - Не удалось декодировать bytes (длина: 29) как UTF-8, используется base64.
[2025-05-18T20:31:00.267+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [DEBUG] [Parser] - Не удалось декодировать bytes (длина: 137) как UTF-8, используется base64.
[2025-05-18 20:31:00] [DEBUG] [Parser] - Не удалось декодировать bytes (длина: 29) как UTF-8, используется base64.
[2025-05-18T20:31:00.267+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [DEBUG] [Parser] - Данные для вставки (ID: 9669): {'message_id': 9669, 'channel_id': 1137503644, 'message_date': datetime.datetime(2025, 5, 18, 13, 25, 12, tzinfo=datetime.timezone.utc), 'text': 'На бирже у нас сейчас ключевой момент и вот почему:\n\n1️⃣ Технически идет завершение треугольника. И отсюда будет молниеносный выход! **__На принятие решения у Вас осталась одна неделя.__**\n\nГляньте ролик выше ⬆️ \n\n2️⃣ Забавно, что это совпадает с долгожданными переговорами в Стамбуле.  Тот случай, когда техника на графиках рулит политикой.\n\nВот ссылки на обзоры. Срочно смотрим и готовимся! ⬇️\n\n[**➡️ Ютуб**](https://youtu.be/5AwSbmokQz8)\n\n[**➡️ Рутуб**](https://rutube.ru/video/5ee7f6f9a8012d868d2e43ecf69c6ba2/)\n\n[**➡️ ВК.видео**](https://vk.com/trader_chernyh?z=video-98605354_456239285%2F2864508e17832f796a%2Fpl_wall_314989763)\n\n__Забавно, что точно такой же тезис после просмотра моего ролика, растащили себе инфоцыгане. Гопоте на пиво не хватает)__ __Который__ __раз воруют идеи__', 'sender_id': -1001137503644, 'views': 18749, 'forwards': 36, 'is_reply': False, 'reply_to_msg_id': None, 'has_media': True, 'raw_data_type': 'Json'}
[2025-05-18T20:31:00.308+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [INFO] [Parser] - Сохранение в БД завершено. Новых записей: 0, пропущено (ошибки/дубликаты): 2.
[2025-05-18 20:31:00] [INFO] [Parser] - Результаты сохранения в БД: 0 новых, 2 пропущено.
[2025-05-18 20:31:00] [ERROR] [Parser] - Ни одно из полученных сообщений не было сохранено в БД из-за ошибок.
[2025-05-18T20:31:00.308+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [ERROR] [Parser] - Критическая ошибка в main: Критическая ошибка: не удалось сохранить сообщения в БД.
Traceback (most recent call last):
  File "/app/telegram_parser.py", line 376, in main
    raise Exception("Критическая ошибка: не удалось сохранить сообщения в БД.")
Exception: Критическая ошибка: не удалось сохранить сообщения в БД.
[2025-05-18 20:31:00] [INFO] [Parser] - Запись данных XCom в файл: /airflow/xcom/return.json
[2025-05-18T20:31:00.309+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [INFO] [Parser] - Создана директория для XCom: /airflow/xcom
[2025-05-18T20:31:00.309+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [INFO] [Parser] - Данные XCom успешно записаны: {'channel_id': 1137503644, 'target_date_str': '2025-05-18', 'parsed_count': 2, 'saved_count': 0, 'status': 'failure', 'error_type': None, 'error_message': 'Критическая ошибка: не удалось сохранить сообщения в БД.'}
[2025-05-18 20:31:00] [INFO] [Parser] - Отключение от Telegram...
[2025-05-18T20:31:00.310+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [INFO] [Parser] - Disconnecting from 149.154.167.51:443/TcpFull...
[2025-05-18 20:31:00] [DEBUG] [Parser] - Closing current connection...
[2025-05-18T20:31:00.311+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [DEBUG] [Parser] - Cancelling 0 pending message(s)...
[2025-05-18 20:31:00] [INFO] [Parser] - Disconnection from 149.154.167.51:443/TcpFull complete!
[2025-05-18T20:31:00.317+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [INFO] [Parser] - Соединение с Telegram закрыто.
[2025-05-18 20:31:00] [INFO] [Parser] - Закрытие соединения с БД...
[2025-05-18 20:31:00] [INFO] [Parser] - Соединение с БД закрыто.
[2025-05-18T20:31:00.317+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [INFO] [Parser] - --- Скрипт парсера завершен с кодом выхода: 1 ---
[2025-05-18T20:31:00.317+0000] {docker.py:429} INFO - [2025-05-18 20:31:00] [INFO] [Parser] - Перехвачен SystemExit с кодом 1. Завершение (из __main__).
[2025-05-18 20:31:00] [INFO] [Parser] - Скрипт парсера окончательно завершается с кодом 1 (из __main__ блока).
[2025-05-18T20:31:00.551+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-05-18T20:31:00.553+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=telegram_summary_channel_1137503644, task_id=parse_channel_posts, execution_date=20250518T203057, start_date=20250518T203058, end_date=20250518T203100
[2025-05-18T20:31:00.563+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 60 for task parse_channel_posts (Docker container failed: {'StatusCode': 1}; 231)
[2025-05-18T20:31:00.577+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-18T20:31:00.598+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
